name: my_app  # 这里填写你的项目名称
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluro: ^2.0.5
  provider: ^6.0.0  # 修改后的版本约束
  flutter_html: ^3.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dio: ^5.8.0+1



flutter:
  uses-material-design: true

  assets:
    - images/baidu.png
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
